### ISSUE TITLE
How to list the all debugs sets  ? Missing Function

### ISSUE THREAD

**Issue by Th4nat0s** [x64dbg/x64dbgpy#29]
Hello guys...

I had a question that https://github.com/x64dbg/x64dbgpy/blob/v25/pluginsdk/_scriptapi_debug.h does not answer.

How could we programatically list all set breakpoints  ?

**Comment by Dagobert-** [comment]
Word. No doubt. For sure.

On Oct 18, 2018 21:46, "Thanat0s" <notifications@github.com> wrote:

Hello guys...

I had a question that
https://github.com/x64dbg/x64dbgpy/blob/v25/pluginsdk/_scriptapi_debug.h
does not answer.

How could we programatically list all set breakpoints  ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/x64dbg/x64dbgpy/issues/29>, or mute the thread

**Comment by asketen** [comment]
Why do I keep getting these mails? Im not even a programmer.

Den fre 19 okt. 2018 08:02Dagobert- <notifications@github.com> skrev:

> Word. No doubt. For sure.
>

**Comment by jahmezz** [comment]
this is the programmer life calling your name

**Comment by SabedMako** [comment]
Putain mais qui êtes vous?

Le 19 oct. 2018 21:13, asketen <notifications@github.com> a écrit :
Why do I keep getting these mails? Im not even a programmer.

Den fre 19 okt. 2018 08:02Dagobert- <notifications@github.com> skrev:

> Word. No doubt. For sure.
>

**Comment by asketen** [comment]
Haha I guess so. Is there a way to unsubscribe from these?

Den fre 19 okt. 2018 21:35James Kahng <notifications@github.com> skrev:

> this is the programmer life calling your name
>

**Comment by Nukem9** [comment]
@Dagobert- 
@asketen 
@jahmezz 
@SabedMako 

https://github.com/x64dbg/x64dbg/issues/1863#issuecomment-361054182
```Everybody who is still subscribed to this and doesn't know why: change your password. You will not see anything in your audit log, but your credentials were used in a Github API call to subscribe to this repo.```

I'm deleting your comments since they (obviously) aren't relevant. You can unsubscribe by clicking the link in the Github email.


@Th4nat0s 
https://github.com/x64dbg/x64dbgpy/blob/v25/pluginsdk/bridgemain.h#L843 DbgGetBpList()

**Comment by Th4nat0s** [comment]
Thanks for your help @Nukem9 ...but for simple humans like me :) 

in the .h file we see DbgGetBpList() needs two parameters and return an integer
The first one is the type of breakpoint quite easy to understand in the code..

```
typedef enum
{
    bp_none = 0,
    bp_normal = 1,
    bp_hardware = 2,
    bp_memory = 4,
    bp_dll = 8,
    bp_exception = 16
} BPXTYPE;

```
The second one is the structure with Breakpoint and BRIDGEBP structure ... this is called a  "BPMAP structure. 

how to use it  in the debugger in python to fech the list of the break point ??

toto = BPMAP()  <- it doesn't work...

And with a simple dict either.
```
toto = {}
DbgGetBpList(bp_normal, toto )
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: in method 'DbgGetBpList', argument 2 of type 'BPMAP *'

```
My goal is to retrieve in the python the bp list and iterate for.. in need to retrieve state, module label and Address.

**Comment by SabedMako** [comment]
Bon bah moi je vais regarder Vinesauce, le meilleur streamer du monde!!!

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by samsta458** [comment]
I'm taking all of your information. Thanks for the data

**Comment by herosi** [comment]
If you want to just access BPMAP, you can use a function named DbgGetBpList that I have added recently. Although the pre-compiled binary doesn't exist yet, you can compile the latest code and use it.

**Comment by Th4nat0s** [comment]
wow... Thank's :)
